### ISSUE TITLE
Support add type infos for query section

### ISSUE THREAD

**Issue by runjuu** [LeetCode-OpenSource/typed-path-generator#1]
support add type infos for query section like `?foo=123`

**Comment by runjuu** [comment]
something like:
```yaml
paths:
  somePath: !!URL
    path: /some/path/:one
    query:
      id: number
      name: string
  anotherPath: /another/path:two
```
